### ISSUE TITLE
mixins / settings.less overwritten on Build. Butchers custom breakpoint settings.

### ISSUE THREAD

**Issue by nacayoda** [craigcollie/Precursor#3]
Having gone into the /src/mixins/setting.less file to adjust the breakpoints, the file is overwritten with defailts when the project is Built.

Default

@screen-phone-portrait-min:1px;
@screen-phone-portrait-max:480px;
@screen-phone-landscape-min:321px;
@screen-phone-landscape-max:767px;
@screen-tablet-portrait-min:768px;
@screen-tablet-portrait-max:1023px;
@screen-tablet-landscape-min:768px;
@screen-tablet-landscape-max:1169px;
@screen-desktop-min:1190px;

Desired for 850 max-width site

@screen-phone-portrait-min:1px;
@screen-phone-portrait-max:480px;
@screen-phone-landscape-min:321px;
@screen-phone-landscape-max:767px;
@screen-tablet-portrait-min:768px;
@screen-tablet-portrait-max:849px;
@screen-tablet-landscape-min:768px;
@screen-tablet-landscape-max:849px;
@screen-desktop-min:870px;

**Comment by craigcollie** [comment]
@nacayoda you should be able to edit these break points in the Media Queries tab, under settings. The settings.less file is automatically generated every time the project is built.

**Comment by nacayoda** [comment]
How did I miss that?!
To be fair, the guy who trained me on this wonderful tool, was pretty new to it himself.
Thanks for the heads-up!
