### ISSUE TITLE
Setting siteWidth in precursor-grid package = inherited width

### ISSUE THREAD

**Issue by nacayoda** [craigcollie/Precursor#4]
I think setting a siteWidth in the precursor-grid package is hampering nested usage of the col-container elements, as this pixel setting is being inherited by the nested columns.

ie, Set siteWidth to 850px
A col-6 will be 425px
But a new col-container inside this containing a col-12 element will render at 850px.
Inheriting the full hard-width of the site.

<style>
col-container col-container {width:100%} logic needed?
</style>

Or am I missing something?

**Comment by craigcollie** [comment]
I don't think there are any hard-coded pixel widths being rendered, rather a relative % to the containing div. If you're nesting elements, then it should only be a percentage of it's container.

**Comment by nacayoda** [comment]
I see what was occurring.
I was nesting col-container elements inside each other. Totally unessesary.
